### PR TITLE
Final MHAVOCPE drivers

### PR DESCRIPTION
**Pull request by jessaskey**
I just released the final ROM images for v1.00 here -> https://github.com/jessaskey/mhavocpe/tree/master/ROMs  All the CRC's for the new drivers match to what is published there.

### CODE REVIEW

**Comment by Robbbert** [comment]
This branch has conflicts that must be resolved by you.

**Comment by dinkc64** [comment]
wowie, been waiting for this - congrats on the 1.0!  I will be adding it to fbneo hopefully soon.

**Comment by Robbbert** [comment]
Manually applied the changes. Seems to work ok.

**Comment by jessaskey** [comment]
Thanks @Robbbert , Apologies for making you do work on this for me. If you have any interest, I would be happy to send you a Major Havoc 'The Promised End' marquee translite if you want one! :-)

**Pull request merged**
