### PR TITLE
Update mhavocpe driver and add havocpex6 for 0.75 ROM release

### PR DESCRIPTION
**Pull request by jessaskey**
I added the MAME configuration for the BETA processor and associated memory which is unstuffed in the production PCB's. I wanted the driver to be complete to match the hardware. Version 0.75 of the mhavocpe ROM images now have two additional ROM's for the BETA processor and for MAME purposes, the BETA processor may be used. For folks running an actual Major Havoc Production PCB, the BETA is optional and does not need to be populated, ALPHA will adjust accordingly.

Additionally I added a new mhavocpex6 driver which has the correct CSUM's for the 0.75 ROM images that I will also release and publish this week.

One question: I was getting this warning when I run now and I was not able to figure out what was causing it, probably something stupid tho... "   Empty ROM region 'beta' (warning)"

### CODE REVIEW

**Comment by Robbbert** [comment]
I'm going to make a whole new mhavoc driver in the hbmame folder, and not use the mame files at all.

Before I can do anything, I need you to remove all reference to hbmame.lst in this PR (.gitignore, hbmame.lst)

**Comment by jessaskey** [comment]
Okay, should be good to go.. LMK if there is anything else. Im pretty clunky in GitHub with this PRs!

**Comment by Robbbert** [comment]
You've still got entries in .gitignore - these need to be removed as well.

**Comment by jessaskey** [comment]
Okay, I can't seem to get something right on the break or line ending to match but it should be workable now without impact.

**Comment by Robbbert** [comment]
Merged, just sorting out the resulting issues. **The new beta roms have no procedure to be created.** There's nothing in patch_roms.bat, and no other mention of converting them at all.
Also patch_roms.bat has old bsp filenames, I had to do corrections on the batch file before it could be used.

**Comment by jessaskey** [comment]
Ahh, you are correct. Missed them in patch_roms.bat… I just added them and committed to the site plus added a note on the Patching Instructions. Thank you for catching that.

**Comment by Robbbert** [comment]
Thanks, that worked. Now just waiting for the new version to be completed.

**Pull request merged**
