### PR TITLE
Fixed compile and linking errors under Linux.

### PR DESCRIPTION
**Pull request by phulshof**
Hello Robert,

Here are the changes you requested on the PD forums. These are sufficient to make the code compile and link on my Linux machine.

### CODE REVIEW

**Comment by newton9278** [comment]
Hello,
With function, "merge" roms in clrmamepro, set roms is ok but doesn't function in hbmame 0.196.
F5 for actually ->all roms are not functionned.

**Comment by phulshof** [comment]
I'm not an actual user of hbmame; I just needed a compiled version to create the XML that was requested. Since I don't have any of the needed roms, I cannot test actual functionality either.

**Comment by Robbbert** [comment]
phulshof, is this change still required?

**Comment by phulshof** [comment]
Just snowbros.cpp and exidy.cpp. I just found time to compile. :)

**Pull request merged**
