### PR TITLE
Release of ROMv 0.78 English and French, driver updates and CSUM matching

### PR DESCRIPTION
**Pull request by jessaskey**
Sorry for the littany of changes here. I tried to keep it pretty clean but if you want me to pull a fresher version of your repo and merge into that instead, I can, just LMK what you think once you see all this. The ROMs for v0.77 both English and French are at the normal repo here.. https://github.com/jessaskey/mhavocpe/tree/master/ROMs 

thank you!!!
Jess

### CODE REVIEW

**Comment by Robbbert** [comment]
This patch cannot be merged due to conflicts. This is because you've updated the MAME files instead of the HBMAME ones. However, I've copied in the parts that were needed for mhavocpex7 in order to try it out.

Issues:
1. The patched rom for English, 1q is a different checksum to what is in the source. The others are all fine.
2. The French version has English text on the demo screen (FOLLOW ARROWS AND TOUCH REACTOR....)
3. The German version says HIGH SCORE on the high score list instead of whatever the German text would be.
4. In French and German the text for Bonus every 100000 points is corrupted.

**Comment by jessaskey** [comment]
Thank you… I will refresh my fork from the current hbmame repo and get these items fixed up (the csum on 1Q mainly). My fork was from when you first started moving into a hbmame src so I was sorta midstream on your conversion. Apologies again for giving you old files and thank you for fixing them.

Yes, both the French and German ROM versions are not quite finished (this is still pre-release roms, which is the ‘x’ part of the driver name). Im still waiting on translations for the top maze messages etc. BUT, I didn’t catch that 100,000 issue so I will get that fixed now and publish 0.78 and I will switch the HBMAME mhavocpex7 driver to the 0.78 ROM images (all with correct csums), I will get another pull request to you later tonight GMT-6 for you to merge at your convenience.

Jess

**Comment by Robbbert** [comment]
Unfortunately there's still problems. 4 of the English roms don't match checksums, and the text is mostly in French.

**Comment by jessaskey** [comment]
Okay, will fix today and resubmit pull…  my process for this on my end is currently very manual and needs cleaned up badly.

**Comment by jessaskey** [comment]
Okay, I reformatted the ROM's so they now have a language identifier (along with position and version identifiers which were already there) on them to distinguish between the different compilations. It required me to regenerate CSUMs for all the mhavocpex7* drivers which have now been updated in the src file for the driver. I'm also going to move away from the version numbers on the source ROM repository and just put files directly to match HBMAME which will make the process of checking this much easier and I can script some validation tools so these types of issues don't keep coming up.

**Comment by Robbbert** [comment]
Still more problems. The games seem to start up ok, but all of the checksums in all 3 games do not match.
Release of next HBMAME is next Wednesday, can the details be fixed before then?

**Comment by jessaskey** [comment]
Yes, I clearly have a flaw in my process that must be overwriting these ROM images after Im checksumming them…. Geeze, I really did double check all these but something is awry and compiling for different languages really threw a wrench on my compilation and build process due to various reasons, so that is why it has been so messy. Apologies again. Two strikes… hopefully not 3. 😊

**Comment by Robbbert** [comment]
What will you do? There isn't much time left.

**Comment by jessaskey** [comment]
So I have been putting all my changes onto the file hbmame/drivers/mhavoc_hb_cpp..... but im seeing a file mentioned in the conflicts that there is a file called src/hbmame/drivers/mhavoc.cpp..... can you confirm which file is correct. I just re-compiled from my fork of your hbmame repo and all my csums are matching to the ROM images on the public mhavocpe site. Maybe we are on seperate files? Here is the pertinent parts of the driver file with all the correct CSUMS

`ROM_START( mhavocpex7 )
	ROM_REGION( 0x2000, "vectorrom", 0 )
	ROM_LOAD( "mhavocpex7.6kl",  0x00000, 0x2000, CRC(ef7843f8) SHA1(bfd096b0db69188f9032578839c9bd91367f7aae) )

	ROM_REGION( 0x20000, "alpha", 0 )
	ROM_LOAD( "mhavocpex7.1mn",  0x08000, 0x4000, CRC(f043dcaf) SHA1(3f20c20ea601190a52dac50d3281ed09a18a4948) )
	ROM_LOAD( "mhavocpex7.1l",   0x0c000, 0x4000, CRC(da963eab) SHA1(b10872898b12d79cd6cf0651ec61962315b5aff9) )
	//ROM_LOAD( "mhavocpex7.1q",   0x10000, 0x8000, CRC(39c5b2d0) SHA1(9cd68ad1b4a7f68c1c6bdcbc60b3cf5a7a289ea7) )
	ROM_LOAD( "mhavocpex7.1q",   0x10000, 0x8000, CRC(57499813) SHA1(ff53f65fc34c5f4b8d4af78776fb242ac59d536a) )
	ROM_LOAD( "mhavocpex7.1np",  0x18000, 0x8000, CRC(0d362096) SHA1(dccc0509aac7003fee11bf7eeabff81360c226a8) )

	ROM_REGION( 0x8000, "avg", 0 )
	ROM_LOAD( "mhavocpex7.6h",   0x0000, 0x4000, CRC(4129d0e9) SHA1(6fd168de59d684f216a0a0ac45aed0782b18f900) )
	ROM_LOAD( "mhavocpex7.6jk",  0x4000, 0x4000, CRC(9361ed01) SHA1(ea07f8430f7e97e0c62d8df2963bb7b66a45b698) )

	ROM_REGION( 0x10000, "gamma", 0 )
	ROM_LOAD( "mhavocpex7.9s",   0x8000, 0x4000, CRC(9703c51f) SHA1(c010021e0dabc568af2eb1d516726ac21a1c9c98) )

	//ROM_REGION( 0x10000, "beta", 0 )
	//ROM_LOAD( "mhavocpe.1bc",   0x8000, 0x4000, CRC(1b31ae10) SHA1(247726f9ebe4892edc7c9577a7fffc93057fafe5) )
	//ROM_LOAD( "mhavocpe.1d",   0xc000, 0x4000, CRC(e86d6226) SHA1(45e00d62c424cb60c30b63ee2de57a465989d8ee) )

	ROM_REGION( 0x100, "avg:prom", 0 )
	ROM_LOAD( "136002-125.6c",   0x0000, 0x0100, CRC(5903af03) SHA1(24bc0366f394ad0ec486919212e38be0f08d0239) )

	ROM_REGION( 0x40000, "oki", 0 )   /* 256k for ADPCM samples */
	ROM_LOAD( "mhavocpex7.x1", 0x000000, 0x040000, CRC(5cfa1865) SHA1(ab520b4af6a9ffc2593223798fee8026266a722e) )
ROM_END

ROM_START( mhavocpex7de )
	ROM_REGION( 0x2000, "vectorrom", 0 )
	ROM_LOAD( "mhavocpex7de.6kl",  0x00000, 0x2000, CRC(6bc3240f) SHA1(6152a5015a99142d77203fa70f96160ffecd460c) )

	ROM_REGION( 0x20000, "alpha", 0 )
	ROM_LOAD( "mhavocpex7de.1mn",  0x08000, 0x4000, CRC(30fc2132) SHA1(0d07fab70e9e2d606a825837436c242706fa690a) )
	ROM_LOAD( "mhavocpex7de.1l",   0x0c000, 0x4000, CRC(245100c8) SHA1(90333f9ad7b1c4422bc0b68a9a4d59edd9596d65) )
	ROM_LOAD( "mhavocpex7de.1q",   0x10000, 0x8000, CRC(8fb86a78) SHA1(53b3ec55962c7a6f615838005b56de7458147f46) )
	ROM_LOAD( "mhavocpex7de.1np",  0x18000, 0x8000, CRC(c8a86dfb) SHA1(8e3257068ae52095b8f15012a46cc99d9e28242f) )

	ROM_REGION( 0x8000, "avg", 0 )
	ROM_LOAD( "mhavocpex7de.6h",   0x0000, 0x4000, CRC(8df8c6e5) SHA1(b5fadd531f040ef01c9c39810bfe81b800a32f78) )
	ROM_LOAD( "mhavocpex7de.6jk",  0x4000, 0x4000, CRC(5fb0fb0d) SHA1(70f72856cb8ade503b00e43c12ed52bbabbd7ca6) )

	ROM_REGION( 0x10000, "gamma", 0 )
	ROM_LOAD( "mhavocpex7de.9s",   0x8000, 0x4000, CRC(722ade2e) SHA1(212cb5c9201e41e08eada3aec3c77ab8728135b1) )

	//ROM_REGION( 0x10000, "beta", 0 )
	//ROM_LOAD( "mhavocpe.1bc",   0x8000, 0x4000, CRC(1b31ae10) SHA1(247726f9ebe4892edc7c9577a7fffc93057fafe5) )
	//ROM_LOAD( "mhavocpe.1d",   0xc000, 0x4000, CRC(e86d6226) SHA1(45e00d62c424cb60c30b63ee2de57a465989d8ee) )

	ROM_REGION( 0x100, "avg:prom", 0 )
	ROM_LOAD( "136002-125.6c",   0x0000, 0x0100, CRC(5903af03) SHA1(24bc0366f394ad0ec486919212e38be0f08d0239) )

	ROM_REGION( 0x40000, "oki", 0 )   /* 256k for ADPCM samples */
	ROM_LOAD( "mhavocpex7de.x1", 0x000000, 0x040000, CRC(5cfa1865) SHA1(ab520b4af6a9ffc2593223798fee8026266a722e) )
ROM_END

ROM_START( mhavocpex7fr )
	ROM_REGION( 0x2000, "vectorrom", 0 )
	ROM_LOAD( "mhavocpex7fr.6kl",  0x00000, 0x2000, CRC(3d7f8a57) SHA1(cc8cd99003b56805c6eab9c4d26c17c485966d17) )

	ROM_REGION( 0x20000, "alpha", 0 )
	ROM_LOAD( "mhavocpex7fr.1mn",  0x08000, 0x4000, CRC(ad00b995) SHA1(f210a934be809b272bbbd7b3a459df6614e8a8f9) )
	ROM_LOAD( "mhavocpex7fr.1l",   0x0c000, 0x4000, CRC(c01b01fa) SHA1(9965da7863da933a1be1ce32e3db578ce4e54bb4) )
	ROM_LOAD( "mhavocpex7fr.1q",   0x10000, 0x8000, CRC(81ac4eda) SHA1(eeab82e1bad953a72300986c9dcdc02f3113cb06) )
	ROM_LOAD( "mhavocpex7fr.1np",  0x18000, 0x8000, CRC(6cf82736) SHA1(4a17ebd9aac863ce34ff5ef2d139cf319c373502) )

	ROM_REGION( 0x8000, "avg", 0 )
	ROM_LOAD( "mhavocpex7fr.6h",   0x0000, 0x4000, CRC(03fafab0) SHA1(5a27c5cf745d51e76c8af63c7880b0337e1b97f5) )
	ROM_LOAD( "mhavocpex7fr.6jk",  0x4000, 0x4000, CRC(d1b2c758) SHA1(047c328855a6fa930e172b77798d0373027ac0ce) )

	ROM_REGION( 0x10000, "gamma", 0 )
	ROM_LOAD( "mhavocpex7fr.9s",   0x8000, 0x4000, CRC(8620f53c) SHA1(96a05e1410d2d5fa55a35bf88d057101aede6681) )

	//ROM_REGION( 0x10000, "beta", 0 )
	//ROM_LOAD( "mhavocpe.1bc",   0x8000, 0x4000, CRC(1b31ae10) SHA1(247726f9ebe4892edc7c9577a7fffc93057fafe5) )
	//ROM_LOAD( "mhavocpe.1d",   0xc000, 0x4000, CRC(e86d6226) SHA1(45e00d62c424cb60c30b63ee2de57a465989d8ee) )

	ROM_REGION( 0x100, "avg:prom", 0 )
	ROM_LOAD( "136002-125.6c",   0x0000, 0x0100, CRC(5903af03) SHA1(24bc0366f394ad0ec486919212e38be0f08d0239) )

	ROM_REGION( 0x40000, "oki", 0 )   /* 256k for ADPCM samples */
	ROM_LOAD( "mhavocpex7fr.x1", 0x000000, 0x040000, CRC(5cfa1865) SHA1(ab520b4af6a9ffc2593223798fee8026266a722e) )
ROM_END`

**Comment by Robbbert** [comment]
That worked. I did a small cleanup as well, since the TMS device was still included (but not used) in the newest sets.

Now to the file problems, you'll see in the "Files changed" of this PR a number of files that don't exist. That is one reason for the conflicts. Some other files has changes requested that were not needed. Anyway it's all been sorted out, so I can close this now.

**Pull request closed without merging**
